name: Axe accessibility testing

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL to be checked (e.g. #publications)"
        required: false

env:
  URL: ""

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Get Chromium version
        run: |
          CHROMIUM_VERSION=$(wget -qO- https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE | cut -d. -f1)
          echo "CHROMIUM_VERSION=$CHROMIUM_VERSION" >> "$GITHUB_ENV"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: ${{ env.CHROMIUM_VERSION }}

      - name: Run axe
        run: |
          npm install --global @axe-core/cli chromedriver@${CHROMIUM_VERSION} http-server
          http-server dist/ &
          axe --chromedriver-path "$(npm root --global)/chromedriver/bin/chromedriver" "http://localhost:8080/${{ github.event.inputs.url || env.URL }}" --load-delay=1500 --exit
